### ISSUE TITLE
Animation in small screen size in menu

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#134]
Hi, when the size of the screen is small, the options in the bar from above is found in the menu. By cons there is no animation when clicked in this mode.

![new option](https://user-images.githubusercontent.com/27307704/39076088-53c7178c-44c7-11e8-922e-fbc8de30da68.gif)

Regards

**Comment by dragosct10** [comment]
Hi, @KonScyence! Yes, we know that and it's difficult to put an animation to it because this is not a normal collapse like the others elements from the sidebar, it is a dropdown and it's when this is hidden have the property `display: none;` and when it is open have `display: block;`, so when these properties are present the animation be activated. Regards, Dragos
