### ISSUE TITLE
Navbar fixed on top

### ISSUE THREAD

**Issue by wellwind** [creativetimofficial/ct-material-dashboard-pro#15]
Is there any to fix to navbar to top?

thanks :)

**Comment by alexandru-paduraru** [comment]
Hi @wellwind, please check this issue where we explain how to achieve that: https://github.com/creativetimofficial/material-dashboard/issues/2 

Let us know if everything is fine.

Best,
Alex

**Comment by mndotmail** [comment]
Instead of modifying the core files; how can I have the `.navbar-fixed-top` work, as it should work on bootstrap.

**Comment by alexandru-paduraru** [comment]
@mndotmail unfortunately, at this moment you need to change the HTML structure, so the navbar will be outside of the `div.main-content` because the scroll is done inside the `div.main-content, and the HTML cannot handle a fixed position to the top inside that scrolling area. We will think of different options in future to make that, or if you have any ideas please let us know, we would be glad to check them.

Best,
Alex
