### ISSUE TITLE
material dasboard pro 2.1.0 and modals 

### ISSUE THREAD

**Issue by simonb0** [creativetimofficial/ct-material-dashboard-pro#215]
- [ X ] I am running the latest version - CT Material Dashboard Pro 2.1.0
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

Hello.
I use the Creative Tim Material Dashboard Pro 2.1.0 on a new project.
I use the example dashboard.php and edited some content and added modals.
I haven´t modified any other files and haven´t added any JS.

The Problem:
The modals are opening as expected, but i can't close them - not by clicking inside or outside the modal.
There are no errors in the console.

I´ve tested a few things and discovered, that when i delete the `class="sidebar"` from the sidebar-div the modals are working fine and can be closed as expected.

Any idea or suggestions for this problem?
Thank you,
Simon

edit-01: As advised, i don´t include the demo.js in the project

**Comment by groovemen** [comment]
Hello @simonb0,

Thank you for using our products, I will ask you to send us a link to your project if it's possible to check for a solution because it's hard to figure out what happens. It could be for example the z-index of the modal. 

 Please let us know if we can help you with anything else.

All the best,
Stefan
