### ISSUE TITLE
card paddings are not configurable via variables

### ISSUE THREAD

**Issue by Qvatra** [creativetimofficial/ct-material-dashboard-pro#238]
# Expected Behavior

cards x paddings are hardcoded to 20px

# Current Behavior

card paddings should be configurable. Apparently $padding-card-body-x is the best candidate for that.

# Failure Information (for bugs)
in _cards.scss on line 352:
`    padding: $padding-card-body-y 20px;`

Why I can not just edit _cards.scss?
it's because we keep theme files intact to be able to update to the latest in the future.

**Comment by groovemen** [comment]
Hello @Qvatra, 

Thank you for using our products and for this constructive feedback. I will ask you to set a variable ($padding-card-body-x ) instead of '20px' and we will assure you that in the next update this kind of changes will no longer have to be made. Please let us know if we can help you with anything else.

Cheers, 
Stefan
