### ISSUE TITLE
data-original-title tooltip appears again after modal dialog closes

### ISSUE THREAD

**Issue by halfsoft** [creativetimofficial/ct-material-dashboard-pro#240]
If you have a button with tooltip that opens a modal window, when you close the modal window the tooltip appears again over the button, and doesn't disappear until you click anywhere on the page.

**Comment by groovemen** [comment]
Hello there, @halfsoft ,

Thank you for your interest in working with our products.
Unfortunately, I cannot replicate your issue, could you please provide me with your code snippet?
Also, I noticed that you declined and erased our Issue Template: 
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

Cheers,
Stefan
