### ISSUE TITLE
Material Design is not working perfect in Safari Browser

### ISSUE THREAD

**Issue by sandeepgolu** [creativetimofficial/ct-material-dashboard-pro#254]
I checked the documentation and found no answer.
![Google Chrome](https://user-images.githubusercontent.com/34332126/64765472-cf6bc000-d561-11e9-970d-b9322ae144d4.png)
![Safari Issues](https://user-images.githubusercontent.com/34332126/64765473-cf6bc000-d561-11e9-8b0d-25ba90d840b8.png)

**Comment by groovemen** [comment]
Hello @sandeepgolu,

Thank you for using our products, It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

Also, I checked this product on the Safari browser and it works just fine. That's why we made this Issue Template to find our more Infos about the user like what Operating System are you using and so on.

<img width="1639" alt="Screenshot 2019-09-13 at 10 45 37" src="https://user-images.githubusercontent.com/21063398/64846055-4f526280-d614-11e9-9444-d572cb2c1eed.png">


Best, 
Stefan
