### ISSUE TITLE
[Feature Request] Add validation in multi step form

### ISSUE THREAD

**Issue by sadnux** [creativetimofficial/ct-material-dashboard-pro#370]
### What is your enhancement?
Perhaps you could add validation in multi step form / wizard when user click on next button, so when conditions are not met in a form panel it will not go to next panel and return to current panel with error sign in each respective field.

**Comment by groovemen** [comment]
Hello @sadnux,

Unfortunately, we cannot help you with custom development, since it is not included in our support terms. Please check all the details [here:](https://www.creative-tim.com/support-terms)
For custom development and work, we have a dedicated team, please refer to our colleagues [here:](https://services.creative-tim.com/
)
Best,
Creative Tim Staff
