### ISSUE TITLE
CSS styles are broken for DataTables.net

### ISSUE THREAD

**Issue by anatskiy** [creativetimofficial/ct-material-dashboard-pro#40]
CSS styles are broken when a newer version (v1.10.15) of DataTables.net is used.

![screenshot](https://cloud.githubusercontent.com/assets/7281783/26277257/5f330b3e-3d85-11e7-9380-1e29bc6fbc11.png)

**Comment by alexandru-paduraru** [comment]
@anatskiy thank you for the information. We've checked with v1.10.12 (the one used in simple Angular 2: http://md-pro-angular2.creative-tim.com/#/tables/datatables.net) and it is not working either for pagination and inputs. It seems the NPM version: https://datatables.net/download/npm and the one that they have on site are different: https://datatables.net/ because one is using the "bootstrap pagination structure" and the other is not using it. Very weird. 

We will create an extra style for the npm version which is not working and release it in the next v1.2.0 update.

Best,
Alex
