### ISSUE TITLE
CSS stylo for print version 

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-material-dashboard-pro#44]
There is a CSS version to use when printing ? Sometimes I need a black/white print version of  a form and its complete useless what I get from the current CSS. This is the only reason I don't using the template for anything after the purchase.

**Comment by alexandru-paduraru** [comment]
@sh1ft-at-github thank you for using our product. This is the first time when somebody is requesting the Print version. Can you please give us more details about what exactly should the print show?

This is what we get at this moment:

<img width="1000" alt="screen shot 2017-06-05 at 11 30 06" src="https://cloud.githubusercontent.com/assets/2517758/26776591/66f2df52-49e2-11e7-9ff2-fa77e57310e0.png">

Best,
Alex

**Comment by sh1ft-at-github** [comment]
Just check http://demos.creative-tim.com/material-dashboard-pro/examples/forms/regular.html  and you see the form fields/elements input checkbox etc are missing (scroll down the page and hit print), selected radio is pink. It would be great if there is a CSS with just black and white. Anyway if this can't be done, no problem because I already gave up on this template because I can't wait for this project.

**Comment by alexandru-paduraru** [comment]
@sh1ft-at-github got it, thank you for the explanation. Yes, we can cover a new CSS just for the print so it should work fine. Did you already integrate another dashboard on your project?

Best,
Ale
